// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaTLr3qca2eoegPg0RKuV1qMa8GcMZAGw',
    appId: '1:523920439041:web:6ee2f1b5046997741a8d00',
    messagingSenderId: '523920439041',
    projectId: 'dailymart-55405',
    authDomain: 'dailymart-55405.firebaseapp.com',
    storageBucket: 'dailymart-55405.firebasestorage.app',
    measurementId: 'G-QSLFNMBPFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6TdiQoHvEa2axqtc7fCN1GD0OHkr7qpw',
    appId: '1:523920439041:android:ed09fe3f3f09bce11a8d00',
    messagingSenderId: '523920439041',
    projectId: 'dailymart-55405',
    storageBucket: 'dailymart-55405.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaTLr3qca2eoegPg0RKuV1qMa8GcMZAGw',
    appId: '1:523920439041:web:6293d8f3a31181591a8d00',
    messagingSenderId: '523920439041',
    projectId: 'dailymart-55405',
    authDomain: 'dailymart-55405.firebaseapp.com',
    storageBucket: 'dailymart-55405.firebasestorage.app',
    measurementId: 'G-SRCH9HSFFM',
  );
}
